### ISSUE TITLE
Update yearly Copyright @year (at the bottom of the page)

### ISSUE THREAD

**Issue by imhicihu** [imhicihu/Enlaces#8]
- [x] task to iCloud Calendar -> done
- [x] script to update Copyright @year automatically

**Comment by kant** [comment]
resolved #[5af0a3c396226049e489e93ae75737198cbab278](https://github.com/imhicihu/Enlaces/commit/5af0a3c396226049e489e93ae75737198cbab278)

**Comment by imhicihu** [comment]
resolved 5af0a3c396226049e489e93ae75737198cbab278
